# Generated by Django 3.1.5 on 2021-01-20 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_product_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_product_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='SoftwarePlanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_softwareplanlog_objects', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_log', to='users.product')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_softwareplanlog_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'software_plan_log',
                'verbose_name_plural': 'software_plans_log',
                'db_table': 'software_plans_log',
            },
        ),
        migrations.CreateModel(
            name='SoftwarePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_softwareplan_objects', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='users.product')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_softwareplan_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'software_plan',
                'verbose_name_plural': 'software_plans',
                'db_table': 'software_plans',
            },
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_servicelog_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_servicelog_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'service_log',
                'verbose_name_plural': 'service_logs',
                'db_table': 'service_logs',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_service_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_service_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Productid', models.BigIntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_productlog_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_productlog_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product_log',
                'verbose_name_plural': 'product_logs',
                'db_table': 'product_logs',
            },
        ),
        migrations.CreateModel(
            name='PeriodLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=50)),
                ('NoOfDays', models.BigIntegerField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_periodlog_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_periodlog_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'period_log',
                'verbose_name_plural': 'period_logs',
                'db_table': 'period_logs',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=50)),
                ('NoOfDays', models.BigIntegerField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_period_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_period_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'period',
                'verbose_name_plural': 'periods',
                'db_table': 'periods',
            },
        ),
        migrations.CreateModel(
            name='CurrencyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_currencylog_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_currencylog_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'currency_logs',
                'verbose_name_plural': 'currency_log',
                'db_table': 'currency_log',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_currency_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_currency_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currency',
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='BusinessTypeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('BusinessTypeid', models.BigIntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_businesstypelog_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_businesstypelog_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'business_type_log',
                'verbose_name_plural': 'business_type_logs',
                'db_table': 'business_type_logs',
            },
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Action', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_businesstype_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_businesstype_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'business_type',
                'verbose_name_plural': 'business_type',
                'db_table': 'business_types',
            },
        ),
    ]
