# Generated by Django 3.1.5 on 2021-08-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
