# Generated by Django 3.1.5 on 2021-09-20 15:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0091_auto_20210920_1556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_activitylog_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('InvoiceID', models.CharField(max_length=128)),
                ('TransactionDate', models.DateTimeField()),
                ('VoucherNo', models.CharField(max_length=128)),
                ('TaxAmount', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('GrandTotal', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('CompanyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.companies')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_einvoice_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_einvoice_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'e_invoice',
                'db_table': 'e_invoice',
            },
        ),
    ]
