# Generated by Django 3.1.5 on 2021-09-30 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0093_auto_20210929_1521'),
        ('users', '0006_einvoice_vouchertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('Device_Code', models.CharField(max_length=50)),
                ('Application_Version', models.CharField(max_length=50)),
                ('Device_Name', models.CharField(max_length=50)),
                ('VanId', models.BigIntegerField(blank=True, null=True)),
                ('CompanyProductId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.companyproduct')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_userdevicedetails_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_userdevicedetails_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_device_details',
                'verbose_name_plural': 'user_device_details',
                'db_table': 'user_device_details',
            },
        ),
    ]
