# Generated by Django 3.1.5 on 2021-10-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userdevicedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='CompanyId',
            field=models.CharField(max_length=200),
        ),
    ]
