# Generated by Django 3.1.5 on 2021-02-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='GstId',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='Tax1Id',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='Tax2Id',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='Tax3Id',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='VatId',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
