# Generated by Django 3.1.5 on 2021-02-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_saleprice_purchaseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleprice',
            name='IsDefault',
            field=models.BooleanField(default=False),
        ),
    ]
