# Generated by Django 3.1.5 on 2021-02-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210204_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemaster',
            name='TransactionId',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
