# Generated by Django 3.1.5 on 2021-02-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_salemaster_transactionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetails',
            name='TransactionId',
        ),
    ]
