# Generated by Django 3.1.5 on 2021-02-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_saledetails_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemaster',
            name='CompanyProductId',
            field=models.ForeignKey(default='f744b1df-b7d9-4578-8997-3318fe419408', on_delete=django.db.models.deletion.CASCADE, to='web.companyproduct'),
            preserve_default=False,
        ),
    ]
