# Generated by Django 3.1.5 on 2021-02-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_vansettings_device_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='UserName',
            field=models.CharField(default='1', max_length=128),
            preserve_default=False,
        ),
    ]
