# Generated by Django 3.1.5 on 2021-02-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_vansettings_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleaccountledger',
            name='PriceCategoryID',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
