# Generated by Django 3.1.5 on 2021-02-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210208_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanroute',
            name='RouteName',
            field=models.CharField(default='test name', max_length=128),
            preserve_default=False,
        ),
    ]
