# Generated by Django 3.1.5 on 2021-02-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_vanroute_routename'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcategory',
            name='CompanyProductId',
            field=models.ForeignKey(default='22b263f6-4a60-488b-8b97-81e06532bf3c', on_delete=django.db.models.deletion.CASCADE, to='web.companyproduct'),
            preserve_default=False,
        ),
    ]
