# Generated by Django 3.1.5 on 2021-02-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_billwise_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='billwise',
            name='VanId',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
