# Generated by Django 3.1.5 on 2021-02-09 11:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_billwise_vanid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecieptDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionId', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('voucherNumber', models.BigIntegerField()),
                ('RecieptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.reciept')),
            ],
            options={
                'verbose_name': 'web_reciept_detail',
                'verbose_name_plural': 'web_reciept_details',
                'db_table': 'web_reciept_details',
            },
        ),
    ]
