# Generated by Django 3.1.5 on 2021-02-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_saleaccountledger_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseledger',
            name='VanId',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reciept',
            name='Van_ID',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
