# Generated by Django 3.1.5 on 2021-02-13 05:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20210212_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciept',
            old_name='NetAmount',
            new_name='TotalAmount',
        ),
        migrations.AddField(
            model_name='recieptdetail',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='recieptdetail',
            name='Due_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
