# Generated by Django 3.1.5 on 2021-02-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_reciept_cashaccountid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='Allow_Receipt_Discount',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
