# Generated by Django 3.1.5 on 2021-02-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_vansettings_allow_receipt_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recieptdetail',
            old_name='voucherNumber',
            new_name='VoucherNumber',
        ),
    ]
