# Generated by Django 3.1.5 on 2021-02-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20210218_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='Allow_Cash_Sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vansettings',
            name='Show_Inclusive_Field',
            field=models.BooleanField(default=False),
        ),
    ]
