# Generated by Django 3.1.5 on 2021-02-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_auto_20210218_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='Allow_Receipt_Discount1',
            field=models.BooleanField(default=False),
        ),
    ]
