# Generated by Django 3.1.5 on 2021-02-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_vansettings_allow_receipt_discount1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vansettings',
            name='Allow_Receipt_Discount',
        ),
    ]
