# Generated by Django 3.1.5 on 2021-02-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_remove_vansettings_allow_receipt_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vansettings',
            old_name='Allow_Receipt_Discount1',
            new_name='Allow_Receipt_Discount',
        ),
    ]
