# Generated by Django 3.1.5 on 2021-02-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_auto_20210222_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleaccountledger',
            name='BillwiseApplicable',
            field=models.BooleanField(default=False),
        ),
    ]
