# Generated by Django 3.1.5 on 2021-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_lastsalesprice_van_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='Show_Last_Sales_Price',
            field=models.BooleanField(default=False),
        ),
    ]
