# Generated by Django 3.1.5 on 2021-03-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_auto_20210303_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
