# Generated by Django 3.1.5 on 2021-03-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_auto_20210315_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='VanId',
            field=models.BigIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
