# Generated by Django 3.1.5 on 2021-03-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_saleorder_vanid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='TaxType',
            field=models.CharField(max_length=128),
        ),
    ]
