# Generated by Django 3.1.5 on 2021-03-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_auto_20210316_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockorder',
            name='TransactionID',
            field=models.BigIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
