# Generated by Django 3.1.5 on 2021-04-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_stockorder_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='PriceCategoryID',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
