# Generated by Django 3.1.5 on 2021-04-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_saleaccountledger_ledgercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleaccountledger',
            name='LedgerCode',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
