# Generated by Django 3.1.5 on 2021-04-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_auto_20210407_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('VanId', models.BigIntegerField()),
                ('CompanyProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.companyproduct')),
            ],
            options={
                'verbose_name': 'database_detail',
                'db_table': 'database_detail',
            },
        ),
    ]
