# Generated by Django 3.1.5 on 2021-04-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_databasedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasedetail',
            name='file',
            field=models.ImageField(null=True, upload_to='DB/'),
        ),
    ]
