# Generated by Django 3.1.5 on 2021-04-23 05:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_vansettings_voucherprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetails',
            name='CostPerPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
