# Generated by Django 3.1.5 on 2021-04-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_saledetails_costperprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'build_version',
                'db_table': 'build_version',
            },
        ),
    ]
