# Generated by Django 3.1.5 on 2021-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='PriceDecimalPoint',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vansettings',
            name='Sales_Invoice_Edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vansettings',
            name='Sales_price_lessthan_Purchase_price',
            field=models.BooleanField(default=False),
        ),
    ]
