# Generated by Django 3.1.5 on 2021-04-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0056_auto_20210430_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='QtyDecimalPoint',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vansettings',
            name='PriceDecimalPoint',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vansettings',
            name='Sales_price_lessthan_Purchase_price',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
