# Generated by Django 3.1.5 on 2021-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0058_auto_20210503_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetails',
            name='StockOrderNo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stockorder',
            name='VanID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
