# Generated by Django 3.1.5 on 2021-05-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_auto_20210508_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockorder',
            name='VanID',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
