# Generated by Django 3.1.5 on 2021-05-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_auto_20210510_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemaster',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
