# Generated by Django 3.1.5 on 2021-05-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_auto_20210528_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemaster',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
