# Generated by Django 3.1.5 on 2021-05-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_auto_20210530_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasedetail',
            name='file',
            field=models.FileField(null=True, upload_to='DB/'),
        ),
    ]
