# Generated by Django 3.1.5 on 2021-05-31 06:04

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_auto_20210531_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasedetail',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='DB/'),
        ),
    ]
