# Generated by Django 3.1.5 on 2021-05-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_auto_20210531_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasedetail',
            name='file',
            field=models.FileField(null=True, upload_to='DB/'),
        ),
    ]
