# Generated by Django 3.1.5 on 2021-05-31 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_auto_20210531_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasedetail',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
