# Generated by Django 3.1.5 on 2021-06-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_databasedetail_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
