# Generated by Django 3.1.5 on 2021-06-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_auto_20210613_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemaster',
            name='salesOrderMasterID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='stockOrderMasterID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
