# Generated by Django 3.1.5 on 2021-06-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_auto_20210614_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='stockOrderMasterID',
        ),
    ]
