# Generated by Django 3.1.5 on 2021-06-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_remove_saleorder_stockordermasterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderdetails',
            name='stockOrderMasterID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
