# Generated by Django 3.1.5 on 2021-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0072_vansettings_vansaleroundoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
