# Generated by Django 3.1.5 on 2021-06-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0073_auto_20210626_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockorder',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
