# Generated by Django 3.1.5 on 2021-06-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0074_auto_20210626_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
