# Generated by Django 3.1.5 on 2021-06-29 05:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0075_auto_20210626_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ProductId', models.BigIntegerField()),
                ('PriceListId', models.BigIntegerField()),
                ('BranchId', models.BigIntegerField()),
                ('UnitName', models.CharField(max_length=128)),
                ('PurchasePrice', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('SalePrice', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('SalePrice1', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('SalePrice2', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('SalePrice3', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('MultiFactor', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('AutoBarcode', models.BigIntegerField()),
                ('Barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('SyncDate', models.DateTimeField()),
                ('IsDefault', models.BooleanField(default=False)),
                ('CompanyProductId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.companyproduct')),
                ('SaleProductId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.saleproduct')),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_saleproductprice_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_saleproductprice_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sale_product_price',
                'db_table': 'web_sale_product_price',
            },
        ),
    ]
