# Generated by Django 3.1.5 on 2021-07-06 06:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0077_saleproduct_minimumsalesprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='CashBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
