# Generated by Django 3.1.5 on 2021-07-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0079_auto_20210714_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereturnmaster',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salereturnmaster',
            name='RefferenceBillDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
