# Generated by Django 3.1.5 on 2021-07-26 09:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0080_auto_20210716_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousestock',
            name='Stock',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
