# Generated by Django 3.1.5 on 2021-07-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0081_auto_20210726_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='EditExpensebeforeSync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vansettings',
            name='EditPaymentinsalesbeforeSync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vansettings',
            name='EditReceiptbeforeSync',
            field=models.BooleanField(default=False),
        ),
    ]
