# Generated by Django 3.1.5 on 2021-08-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0083_salesreturnbillwisedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='EditsalesOrderbeforeSync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vansettings',
            name='EditsalesReturnbeforeSync',
            field=models.BooleanField(default=False),
        ),
    ]
