# Generated by Django 3.1.5 on 2021-08-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0084_auto_20210814_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='CountryId',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vansettings',
            name='PlaceofSupplay',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
