# Generated by Django 3.1.5 on 2021-08-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0085_auto_20210830_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vansettings',
            old_name='PlaceofSupplay',
            new_name='PlaceofSupply',
        ),
    ]
