# Generated by Django 3.1.5 on 2021-08-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0086_auto_20210830_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemaster',
            name='PlaceofSupply',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
