# Generated by Django 3.1.5 on 2021-08-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0087_salemaster_placeofsupply'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledger',
            name='PlaceofSupply',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='accountledgerlog',
            name='PlaceofSupply',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='saleaccountledger',
            name='PlaceofSupply',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
