# Generated by Django 3.1.5 on 2021-09-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_activitylog_is_deleted'),
        ('web', '0088_auto_20210830_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydevices',
            name='IsTrialVersion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companydevices',
            name='ProductExpiryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydeviceslog',
            name='IsTrialVersion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companydeviceslog',
            name='ProductExpiryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='software_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_plan', to='users.softwareplan'),
        ),
        migrations.AddField(
            model_name='companyproductlog',
            name='software_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software_plan_log', to='users.softwareplan'),
        ),
    ]
