# Generated by Django 3.1.5 on 2021-09-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0090_auto_20210920_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='companieslog',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='companieslog',
            name='cr_cin_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='companieslog',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='companieslog',
            name='register_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='companieslog',
            name='tagline',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='companieslog',
            name='trn_vat_gst',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
