# Generated by Django 3.1.5 on 2021-09-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0091_auto_20210920_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemaster',
            name='check_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
