# Generated by Django 3.1.5 on 2021-11-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0093_auto_20210929_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='vansettings',
            name='DatabaseName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vansettings',
            name='EnablePortForward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vansettings',
            name='IPAddress',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vansettings',
            name='Port',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
