# Generated by Django 3.1.5 on 2021-11-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0095_vanpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billwise',
            name='Date',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='billwise',
            name='Due_Date',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='Date',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='DueDate',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
