# Generated by Django 3.1.5 on 2021-11-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0096_auto_20211111_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VanPassword',
        ),
    ]
