# Generated by Django 3.1.5 on 2021-11-11 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0097_delete_vanpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='VanPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('is_expired', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_vanpassword_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_vanpassword_objects', to=settings.AUTH_USER_MODEL)),
                ('vansettings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.vansettings')),
            ],
            options={
                'verbose_name': 'van_settigns_password',
                'verbose_name_plural': 'van_settigns_passwords',
                'db_table': 'van_settigns_passwords',
            },
        ),
    ]
