# Generated by Django 3.1.5 on 2021-11-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0098_vanpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanpassword',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanpassword',
            name='time_str',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
