# Generated by Django 3.1.5 on 2021-11-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0099_auto_20211111_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='Description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
