# Generated by Django 3.1.5 on 2022-01-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0100_auto_20211112_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='GUID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='salemaster',
            name='GUID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='salereturnmaster',
            name='GUID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stockorder',
            name='GUID',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
