# Generated by Django 3.1.5 on 2022-01-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0104_remove_salereturnmaster_billmargin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salemaster',
            name='BillMargin',
        ),
    ]
