# Generated by Django 3.1.5 on 2021-01-20 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readonly', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('down', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'mode',
                'verbose_name_plural': 'mode',
                'db_table': 'mode',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counter', models.PositiveIntegerField()),
                ('prefix', models.CharField(max_length=128)),
                ('project_prefix', models.CharField(max_length=128)),
                ('product_prefix', models.CharField(max_length=128)),
                ('purchase_prefix', models.CharField(max_length=128)),
                ('sale_prefix', models.CharField(max_length=128)),
                ('payment_prefix', models.CharField(max_length=128)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings',
                'db_table': 'setting',
                'ordering': ('prefix',),
            },
        ),
    ]
